/*
 * WeldingView.java
 */

package welding;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.math.*;

/**
 * The application's main frame.
 */
public class WeldingView extends FrameView implements UserInterface,DBQuery{
   
    public WeldingView(SingleFrameApplication app) {
        super(app);
        

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = WeldingApp.getApplication().getMainFrame();
            aboutBox = new WeldingAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        WeldingApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(welding.WeldingApp.class).getContext().getResourceMap(WeldingView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(welding.WeldingApp.class).getContext().getActionMap(WeldingView.class, this);
        jRadioButton1.setAction(actionMap.get("englishUnits")); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        jRadioButton2.setAction(actionMap.get("metricUnits")); // NOI18N
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Carbon Steel", "Stainless Steel", "Nickel Alloy", "Aluminum Alloys", "Titanium Alloys" }));
        jComboBox1.setAction(actionMap.get("changeFillerMaterial")); // NOI18N
        jComboBox1.setName("jComboBox1"); // NOI18N

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SAW", "GMAW (98Ar-2O2)", "GMAW (75Ar-25CO2)", "GMAW CO2", "FCAW (Gas)", "FCAW (Self Shield)", "SMAW (12\" Stick)", "SMAW (14\" Stick)", "SMAW (18\" Stick)", "GTAW" }));
        jComboBox2.setAction(actionMap.get("changeProcess")); // NOI18N
        jComboBox2.setName("jComboBox2"); // NOI18N

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10%", "15%", "20%", "25%", "30%", "35%", "40%", "45%", "50%", "55%", "60%", "65%", "70%", "75%", "80%", "85%", "90%", "95%", "100%" }));
        jComboBox4.setAction(actionMap.get("changeWelderEfficiency")); // NOI18N
        jComboBox4.setName("jComboBox4"); // NOI18N

        jLabel19.setText(resourceMap.getString("jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N

        jLabel28.setText(resourceMap.getString("jLabel28.text")); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N

        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N

        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N

        jLabel34.setText(resourceMap.getString("jLabel34.text")); // NOI18N
        jLabel34.setName("jLabel34"); // NOI18N

        jLabel35.setText(resourceMap.getString("jLabel35.text")); // NOI18N
        jLabel35.setName("jLabel35"); // NOI18N

        jLabel36.setText(resourceMap.getString("jLabel36.text")); // NOI18N
        jLabel36.setName("jLabel36"); // NOI18N

        jLabel37.setText(resourceMap.getString("jLabel37.text")); // NOI18N
        jLabel37.setName("jLabel37"); // NOI18N

        jLabel38.setText(resourceMap.getString("jLabel38.text")); // NOI18N
        jLabel38.setName("jLabel38"); // NOI18N

        jLabel39.setText(resourceMap.getString("jLabel39.text")); // NOI18N
        jLabel39.setName("jLabel39"); // NOI18N

        jLabel40.setText(resourceMap.getString("jLabel40.text")); // NOI18N
        jLabel40.setName("jLabel40"); // NOI18N

        jLabel41.setText(resourceMap.getString("jLabel41.text")); // NOI18N
        jLabel41.setName("jLabel41"); // NOI18N

        jLabel42.setText(resourceMap.getString("jLabel42.text")); // NOI18N
        jLabel42.setName("jLabel42"); // NOI18N

        jLabel43.setText(resourceMap.getString("jLabel43.text")); // NOI18N
        jLabel43.setName("jLabel43"); // NOI18N

        jLabel44.setText(resourceMap.getString("jLabel44.text")); // NOI18N
        jLabel44.setName("jLabel44"); // NOI18N

        jLabel45.setText(resourceMap.getString("jLabel45.text")); // NOI18N
        jLabel45.setName("jLabel45"); // NOI18N

        jLabel46.setText(resourceMap.getString("jLabel46.text")); // NOI18N
        jLabel46.setName("jLabel46"); // NOI18N

        jLabel47.setText(resourceMap.getString("jLabel47.text")); // NOI18N
        jLabel47.setName("jLabel47"); // NOI18N

        jLabel48.setText(resourceMap.getString("jLabel48.text")); // NOI18N
        jLabel48.setName("jLabel48"); // NOI18N

        jLabel49.setText(resourceMap.getString("jLabel49.text")); // NOI18N
        jLabel49.setName("jLabel49"); // NOI18N

        jLabel50.setText(resourceMap.getString("jLabel50.text")); // NOI18N
        jLabel50.setName("jLabel50"); // NOI18N

        jLabel51.setText(resourceMap.getString("jLabel51.text")); // NOI18N
        jLabel51.setName("jLabel51"); // NOI18N

        jLabel52.setText(resourceMap.getString("jLabel52.text")); // NOI18N
        jLabel52.setName("jLabel52"); // NOI18N

        jLabel53.setText(resourceMap.getString("jLabel53.text")); // NOI18N
        jLabel53.setName("jLabel53"); // NOI18N

        jLabel54.setText(resourceMap.getString("jLabel54.text")); // NOI18N
        jLabel54.setName("jLabel54"); // NOI18N

        jLabel55.setText(resourceMap.getString("jLabel55.text")); // NOI18N
        jLabel55.setName("jLabel55"); // NOI18N

        jLabel56.setText(resourceMap.getString("jLabel56.text")); // NOI18N
        jLabel56.setName("jLabel56"); // NOI18N

        jLabel57.setText(resourceMap.getString("jLabel57.text")); // NOI18N
        jLabel57.setName("jLabel57"); // NOI18N

        jLabel58.setText(resourceMap.getString("jLabel58.text")); // NOI18N
        jLabel58.setName("jLabel58"); // NOI18N

        jLabel59.setText(resourceMap.getString("jLabel59.text")); // NOI18N
        jLabel59.setName("jLabel59"); // NOI18N

        jLabel60.setText(resourceMap.getString("jLabel60.text")); // NOI18N
        jLabel60.setName("jLabel60"); // NOI18N

        jLabel61.setText(resourceMap.getString("jLabel61.text")); // NOI18N
        jLabel61.setName("jLabel61"); // NOI18N

        jLabel62.setText(resourceMap.getString("jLabel62.text")); // NOI18N
        jLabel62.setName("jLabel62"); // NOI18N

        jLabel63.setText(resourceMap.getString("jLabel63.text")); // NOI18N
        jLabel63.setName("jLabel63"); // NOI18N

        jLabel65.setText(resourceMap.getString("jLabel65.text")); // NOI18N
        jLabel65.setName("jLabel65"); // NOI18N

        jLabel66.setText(resourceMap.getString("jLabel66.text")); // NOI18N
        jLabel66.setName("jLabel66"); // NOI18N

        jLabel67.setText(resourceMap.getString("jLabel67.text")); // NOI18N
        jLabel67.setName("jLabel67"); // NOI18N

        jLabel68.setText(resourceMap.getString("jLabel68.text")); // NOI18N
        jLabel68.setName("jLabel68"); // NOI18N

        jLabel70.setText(resourceMap.getString("jLabel70.text")); // NOI18N
        jLabel70.setName("jLabel70"); // NOI18N

        jLabel71.setText(resourceMap.getString("jLabel71.text")); // NOI18N
        jLabel71.setName("jLabel71"); // NOI18N

        jLabel72.setText(resourceMap.getString("jLabel72.text")); // NOI18N
        jLabel72.setName("jLabel72"); // NOI18N

        jLabel73.setText(resourceMap.getString("jLabel73.text")); // NOI18N
        jLabel73.setName("jLabel73"); // NOI18N

        jLabel75.setText(resourceMap.getString("jLabel75.text")); // NOI18N
        jLabel75.setName("jLabel75"); // NOI18N

        jLabel78.setText(resourceMap.getString("jLabel78.text")); // NOI18N
        jLabel78.setName("jLabel78"); // NOI18N

        jLabel79.setText(resourceMap.getString("jLabel79.text")); // NOI18N
        jLabel79.setName("jLabel79"); // NOI18N

        jLabel80.setText(resourceMap.getString("jLabel80.text")); // NOI18N
        jLabel80.setName("jLabel80"); // NOI18N

        jLabel81.setText(resourceMap.getString("jLabel81.text")); // NOI18N
        jLabel81.setName("jLabel81"); // NOI18N

        jLabel82.setText(resourceMap.getString("jLabel82.text")); // NOI18N
        jLabel82.setName("jLabel82"); // NOI18N

        jLabel83.setText(resourceMap.getString("jLabel83.text")); // NOI18N
        jLabel83.setName("jLabel83"); // NOI18N

        jLabel84.setText(resourceMap.getString("jLabel84.text")); // NOI18N
        jLabel84.setName("jLabel84"); // NOI18N

        jLabel85.setText(resourceMap.getString("jLabel85.text")); // NOI18N
        jLabel85.setName("jLabel85"); // NOI18N

        jLabel86.setText(resourceMap.getString("jLabel86.text")); // NOI18N
        jLabel86.setName("jLabel86"); // NOI18N

        jLabel88.setText(resourceMap.getString("jLabel88.text")); // NOI18N
        jLabel88.setName("jLabel88"); // NOI18N

        jLabel89.setText(resourceMap.getString("jLabel89.text")); // NOI18N
        jLabel89.setName("jLabel89"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2)
                        .addGap(212, 212, 212)
                        .addComponent(jLabel19)
                        .addContainerGap(170, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addContainerGap(638, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel15))
                                .addGap(31, 31, 31)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(mainPanelLayout.createSequentialGroup()
                                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel52)
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabel57)
                                                                    .addComponent(jLabel56)
                                                                    .addComponent(jLabel59))
                                                                .addGap(50, 50, 50))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel55)
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel53)
                                                            .addComponent(jLabel51))
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(jLabel60)
                                                            .addComponent(jLabel58))))))
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(37, 37, 37)
                                        .addComponent(jLabel36))
                                    .addComponent(jLabel45)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel49)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel43)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel44))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel38)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                        .addComponent(jLabel40)
                                                        .addGap(45, 45, 45)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel41)
                                                    .addGap(39, 39, 39)))
                                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel42)
                                                .addComponent(jLabel39)
                                                .addComponent(jLabel37)
                                                .addComponent(jLabel46)
                                                .addComponent(jLabel48)
                                                .addComponent(jLabel50))))))
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(105, 105, 105)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel20))
                                .addGap(34, 34, 34)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel62))
                                    .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel66, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel65))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel67))
                                    .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel71))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel80))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel82))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel83, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel84))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel85, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel86))
                                    .addComponent(jLabel88, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel89, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)))
                        .addGap(111, 111, 111))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(jLabel61)
                                .addComponent(jLabel62))
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel21)
                            .addComponent(jLabel63))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel22)
                            .addComponent(jLabel66)
                            .addComponent(jLabel65))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel68)
                            .addComponent(jLabel67))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel24)
                            .addComponent(jLabel38)
                            .addComponent(jLabel70)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel25)
                            .addComponent(jLabel40)
                            .addComponent(jLabel72)
                            .addComponent(jLabel71)
                            .addComponent(jLabel39))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel41)
                                    .addComponent(jLabel42))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel44)
                                            .addComponent(jLabel43))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel45)
                                            .addComponent(jLabel46))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel47)
                                            .addComponent(jLabel48))
                                        .addGap(26, 26, 26))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel27)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel28)
                                        .addGap(4, 4, 4))))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel89)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel88)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel73)
                                .addGap(4, 4, 4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel35)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel75))
                        .addGap(2, 2, 2)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel30)
                    .addComponent(jLabel78))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel52)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel31)
                            .addComponent(jLabel54)
                            .addComponent(jLabel53))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel56)
                            .addComponent(jLabel32)
                            .addComponent(jLabel55))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel57)
                            .addComponent(jLabel33)
                            .addComponent(jLabel58))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel59)
                            .addComponent(jLabel34)
                            .addComponent(jLabel60)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel79)
                            .addComponent(jLabel80))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel81)
                            .addComponent(jLabel82))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel83)
                            .addComponent(jLabel84))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel85)
                            .addComponent(jLabel86))))
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 533, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    WeldingClass newWeld=new WeldingClass();
    QueryClass newQuery=new QueryClass();

    @Action
    public void englishUnits() {
        jRadioButton1.setSelected(true);
        jRadioButton2.setSelected(false);
        newWeld.setUnits(true);
        CalculateWelding();
    }

    @Action
    public void metricUnits() {
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(true);
        newWeld.setUnits(false);
        CalculateWelding();
    }

    Connection connection = null;

    public boolean checkProcess(){
        Pattern p=Pattern.compile("SMAW");
        boolean match;
        Matcher m=p.matcher(newWeld.getProcess());
        match=m.find();
        return match;
    }

    public void SetIndicators(Statement s){
       try{
           s.executeQuery(newQuery.getQueryLegSize());
           ResultSet r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel2.setText(newWeld.getIndicatorName());
            jLabel35.setText(newWeld.getIndicatorValue());
            jLabel36.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryWireFeed());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel8.setText(newWeld.getIndicatorName());
            jLabel41.setText(newWeld.getIndicatorValue());
            jLabel42.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryElectrodeDiam());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel9.setText(newWeld.getIndicatorName());
            jLabel43.setText(newWeld.getIndicatorValue());
            jLabel44.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryTotalLengthOfWeld());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            newWeld.setTotalLengthOfWeld(newWeld.getIndicatorValue());
            jLabel10.setText(newWeld.getIndicatorName());
            jLabel45.setText(newWeld.getIndicatorValue());
            jLabel46.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryTravelSpeed());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel11.setText(newWeld.getIndicatorName());
            jLabel47.setText(newWeld.getIndicatorValue());
            jLabel48.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryGasFlowRate());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel12.setText(newWeld.getIndicatorName());
            jLabel49.setText(newWeld.getIndicatorValue());
            jLabel50.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryCostElectrode());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel14.setText(newWeld.getIndicatorName());
            jLabel52.setText(newWeld.getIndicatorValue());
            jLabel51.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryGasCylinderSize());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorName(r.getObject(1).toString());
            newWeld.setIndicatorValue(r.getObject(2).toString());
            newWeld.setIndicatorUnits(r.getObject(3).toString());
            jLabel17.setText(newWeld.getIndicatorName());
            jLabel57.setText(newWeld.getIndicatorValue());
            jLabel58.setText(newWeld.getIndicatorUnits());
           }
    }
    catch (Exception e){
            System.err.println("Ошибка: "+e.getMessage());
        }
    }

    public void OutputResults(Statement s){
        try{
           s.executeQuery(newQuery.getQueryAmountOfFillerMetalNeeded());
           ResultSet r = s.getResultSet();
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorUnits(r.getObject(1).toString());
            jLabel62.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQuerySizeOfFilletWeld());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorUnits(r.getObject(1).toString());
            jLabel65.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryAmountOfShieldingGasUsed());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorUnits(r.getObject(1).toString());
            jLabel67.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryCost());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setIndicatorUnits(r.getObject(1).toString());
            jLabel80.setText(newWeld.getIndicatorUnits());
            jLabel82.setText(newWeld.getIndicatorUnits());
            jLabel84.setText(newWeld.getIndicatorUnits());
            jLabel86.setText(newWeld.getIndicatorUnits());
           }

           s.executeQuery(newQuery.getQueryFillerMaterialProcess());
           r = s.getResultSet();
           while(r.next())
           {
             newWeld.setAmountOfFillerMetalNeeded(r.getObject(1).toString());
             newWeld.setNumberOfPassesPerJoint(r.getObject(2).toString());
             newWeld.setWeldingElectrodeCost(r.getObject(3).toString());
             jLabel61.setText(newWeld.getAmountOfFillerMetalNeeded());
             jLabel63.setText(newWeld.getNumberOfPassesPerJoint());
             jLabel88.setText("$"+newWeld.getWeldingElectrodeCost());
           }

           s.executeQuery(newQuery.getQueryGasPowerCost());
           r = s.getResultSet();
           while(r.next())
           {
              newWeld.setGasCost(r.getObject(1).toString());
              newWeld.setPowerCost(r.getObject(2).toString());
              jLabel73.setText("$"+newWeld.getGasCost());
              jLabel75.setText("$"+newWeld.getPowerCost());
           }

           s.executeQuery(newQuery.getQueryProcessEfficiency());
           r = s.getResultSet();
           while(r.next())
           {
            newWeld.setActualWeldingTime(r.getObject(1).toString());
            newWeld.setLaborCost(r.getObject(2).toString());
            jLabel72.setText(newWeld.getActualWeldingTime());
            jLabel89.setText("$"+newWeld.getLaborCost());
           }

           s.executeQuery(newQuery.getQueryProcessOutput());
           r = s.getResultSet();
           while(r.next())
           {
              newWeld.setSizeOfFilletWeld(r.getObject(1).toString());
              newWeld.setAmountOfShieldingGasUsed(r.getObject(2).toString());
              newWeld.setNumberOfGasBottlesRequired(r.getObject(3).toString());
              jLabel66.setText(newWeld.getSizeOfFilletWeld());
              jLabel68.setText(newWeld.getAmountOfShieldingGasUsed());
              jLabel70.setText(newWeld.getNumberOfGasBottlesRequired());
           }
          newWeld.setInitialCost(Double.toString(Double.parseDouble(newWeld.getLaborCost())+Double.parseDouble(newWeld.getWeldingElectrodeCost())
                  +Double.parseDouble(newWeld.getGasCost())+Double.parseDouble(newWeld.getPowerCost())));
          BigDecimal dInitial = new BigDecimal(newWeld.getInitialCost());
          jLabel78.setText("$"+dInitial.setScale(2,BigDecimal.ROUND_UP));
          jLabel31.setText("Total cost per "+newWeld.getUnitCost()+" of weld");
          newWeld.setTotalCostPerUnitOfWeld(Double.toString(Double.parseDouble(newWeld.getInitialCost())/Double.parseDouble(newWeld.getTotalLengthOfWeld())));
          BigDecimal d1 = new BigDecimal(newWeld.getTotalCostPerUnitOfWeld());
          jLabel79.setText(d1.setScale(2,BigDecimal.ROUND_UP).toString());
          jLabel32.setText("Filler cost per "+newWeld.getUnitCost()+" of weld");
          newWeld.setFillerCostPerUnitOfWeld(Double.toString(Double.parseDouble(newWeld.getWeldingElectrodeCost())/Double.parseDouble(newWeld.getTotalLengthOfWeld())));
          BigDecimal d2 = new BigDecimal(newWeld.getFillerCostPerUnitOfWeld());
          jLabel81.setText(d2.setScale(2,BigDecimal.ROUND_UP).toString());
          jLabel33.setText("Gas cost per "+newWeld.getUnitCost()+" of weld");
          newWeld.setGasCostPerUnitOfWeld(Double.toString(Double.parseDouble(newWeld.getGasCost())/Double.parseDouble(newWeld.getTotalLengthOfWeld())));
          BigDecimal d3 = new BigDecimal(newWeld.getGasCostPerUnitOfWeld());
          jLabel83.setText(d3.setScale(2,BigDecimal.ROUND_UP).toString());
          jLabel34.setText("Labor cost per "+newWeld.getUnitCost()+" of weld");
          newWeld.setLaborCostPerUnitOfWeld(Double.toString(Double.parseDouble(newWeld.getLaborCost())/Double.parseDouble(newWeld.getTotalLengthOfWeld())));
          BigDecimal d4 = new BigDecimal(newWeld.getLaborCostPerUnitOfWeld());
          jLabel85.setText(d4.setScale(2,BigDecimal.ROUND_UP).toString());
        }
       catch (Exception e){
            System.err.println("Ошибка: "+e.getMessage());
        }
    }

     public void GenerateEnglishQueries(){
             newWeld.setIndicator("Leg Size");
             newQuery.setQueryLegSize("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Wire Feed");
             newQuery.setQueryWireFeed("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Electrode Diam.");
             newQuery.setQueryElectrodeDiam("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Total Length of Weld");
             newQuery.setQueryTotalLengthOfWeld("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Travel Speed");
             newQuery.setQueryTravelSpeed("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Gas Flow Rate");
             newQuery.setQueryGasFlowRate("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Cost Electrode");
             newQuery.setQueryCostElectrode("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Gas Cylinder Size");
             newQuery.setQueryGasCylinderSize("SELECT Indicator_English, English_value, English_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Amount of filler metal needed");
             newQuery.setQueryAmountOfFillerMetalNeeded("SELECT Value_English FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newQuery.setQueryFillerMaterialProcess("SELECT Amount_of_filler_E,Number_of_passes_per_joint,Welding_Electrode_Cost FROM welding.Filler_material_Process WHERE Filler_material='"
                     +newWeld.getFillerMaterial()+"' AND Process='"+newWeld.getProcess()+"'");
             newWeld.setIndicator("Size of fillet weld");
             newQuery.setQuerySizeOfFilletWeld("SELECT Value_English FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Amount of shielding gas used");
             newQuery.setQueryAmountOfShieldingGasUsed("SELECT Value_English FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Cost");
             newQuery.setQueryCost("SELECT Value_English FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newQuery.setQueryProcessOutput("SELECT Size_of_fillet_weld_E,Amount_of_shielding_gas_used_E,Number_of_Gas_Bottles_Required FROM welding.Process_Output WHERE Name_pr='"
                     +newWeld.getProcess()+"'");
             newWeld.setUnitCost("ft");
     }

     public void GenerateMetricQueries(){
             newWeld.setIndicator("Leg Size");
             newQuery.setQueryLegSize("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Wire Feed");
             newQuery.setQueryWireFeed("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Electrode Diam.");
             newQuery.setQueryElectrodeDiam("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Total Length of Weld");
             newQuery.setQueryTotalLengthOfWeld("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Travel Speed");
             newQuery.setQueryTravelSpeed("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Gas Flow Rate");
             newQuery.setQueryGasFlowRate("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Cost Electrode");
             newQuery.setQueryCostElectrode("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Gas Cylinder Size");
             newQuery.setQueryGasCylinderSize("SELECT Indicator_metric, Metric_value, Metric_units FROM welding.Units WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Amount of filler metal needed");
             newQuery.setQueryAmountOfFillerMetalNeeded("SELECT Value_Metric FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newQuery.setQueryFillerMaterialProcess("SELECT Amount_of_filler_M,Number_of_passes_per_joint,Welding_Electrode_Cost FROM welding.Filler_material_Process WHERE Filler_material='"
                     +newWeld.getFillerMaterial()+"' AND Process='"+newWeld.getProcess()+"'");
             newWeld.setIndicator("Size of fillet weld");
             newQuery.setQuerySizeOfFilletWeld("SELECT Value_Metric FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Amount of shielding gas used");
             newQuery.setQueryAmountOfShieldingGasUsed("SELECT Value_Metric FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newWeld.setIndicator("Cost");
             newQuery.setQueryCost("SELECT Value_Metric FROM welding.UnitsConvert WHERE Indicator='"+newWeld.getIndicator()+"'");
             newQuery.setQueryProcessOutput("SELECT Size_of_fillet_weld_M,Amount_of_shielding_gas_used_M,Number_of_Gas_Bottles_Required FROM welding.Process_Output WHERE Name_pr='"
                     +newWeld.getProcess()+"'");
             newWeld.setUnitCost("meter");
     }

     public void GenerateGeneralQueries(){
            if (checkProcess())
                 newQuery.setQueryGasPowerCost("SELECT Gas_Cost,Power_Cost FROM welding.Gas_Power_Cost_Process_Stick WHERE Filler_material='"+newWeld.getFillerMaterial()+
                         "' AND Process_Stick='"+newWeld.getProcess()+"'");
             else
                 newQuery.setQueryGasPowerCost("SELECT Gas_Cost,Power_Cost FROM welding.Gas_Power_Cost WHERE Process='"+newWeld.getProcess()+"'");

           newQuery.setQueryProcessEfficiency("SELECT Actual_welding_time,Labor_Cost FROM welding.Process_Efficiency WHERE Process='"+newWeld.getProcess()+
                   "' AND Welder_Efficiency="+newWeld.getWelderEfficiency());
     }

    public void CalculateWelding(){
     try
        {
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver").newInstance();
            connection = DriverManager.getConnection(
                    "jdbc:odbc:welding");
           }
           catch (Exception e){
            System.err.println("Драйвер JDBC/ODBC не найден. "+e.getMessage());
           }
        
           Statement s = connection.createStatement();
                 
           if (newWeld.getUnits()){
               GenerateEnglishQueries();         
           }
           if (!newWeld.getUnits()){
               GenerateMetricQueries();             
           }

           GenerateGeneralQueries();
           
           SetIndicators(s);
           OutputResults(s);
   
        }
        catch (Exception e){
            System.err.println("Ошибка: "+e.getMessage());
        }
    }

    @Action
    public void changeFillerMaterial() {
        newWeld.setFillerMaterial(jComboBox1.getSelectedItem().toString());
        CalculateWelding();
    }

    @Action
    public void changeProcess() {
        newWeld.setProcess(jComboBox2.getSelectedItem().toString());
        CalculateWelding();
    }

    @Action
    public void changeWelderEfficiency() {
        newWeld.setWelderEfficiency((jComboBox4.getSelectedIndex()+2)*5);
        CalculateWelding();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
